config/routes.rb
Rails.application.routes.draw do
  concern :accountable do
    resources :bank_accounts, except: :index
  end

  resources :counterparties, concerns: :accountable
  resources :businesses, concerns: :accountable
  resources :document_templates
  resources :documents, except: :new do
    get 'new/:type', to: 'documents#new', as: :new, on: :collection
  end

  devise_for :users

  authenticated :user do
    root to: "dashboard#show", as: :authenticated_root
  end

  root to: "pages#home"
end

app/controllers/businesses_controller.rb
class BusinessesController < CustomerController
  before_action :set_business, only: [:show, :edit, :update, :destroy]

  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = current_user.businesses
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)
    @business.owner = current_user

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: "Business was successfully created." }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: "Business was successfully updated." }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: "Business was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_business
    @business = Business.find(params[:id])
    @bank_accounts = @business.bank_accounts
  end

  # Only allow a list of trusted parameters through.
  def business_params
    params.require(:business).permit(:company_full_name, :company_short_name, :signatory_person, :signatory_person_genitive, :signatory_basis, :signatory_basis_genitive, :inn, :kpp, :ogrn, :legal_address, :real_address, :post_address, :phone, :email)
  end
end

app/views/businesses/_form.html.erb
<%= simple_form_for(@business) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :company_full_name %>
    <%= f.input :company_short_name %>
    <%= f.input :signatory_person %>
    <%= f.input :signatory_person_genitive %>
    <%= f.input :signatory_basis %>
    <%= f.input :signatory_basis_genitive %>
    <%= f.input :inn %>
    <%= f.input :kpp %>
    <%= f.input :ogrn %>
    <%= f.input :legal_address %>
    <%= f.input :real_address %>
    <%= f.input :post_address %>
    <%= f.input :phone %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing Business</h1>

<%= render 'form', business: @business %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<h1>Businesses</h1>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th>Company name</th>
      <th>Inn</th>
      <th>Kpp</th>
      <th>Ogrn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td><%= business.company_short_name %></td>
        <td><%= business.inn %></td>
        <td><%= business.kpp %></td>
        <td><%= business.ogrn %></td>
        <td><%= link_to 'Show', business %></td>
        <td><%= link_to 'Edit', edit_business_path(business) %></td>
        <td><%= link_to 'Destroy', business, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business', new_business_path, class: 'btn btn-primary' %>

app/views/businesses/new.html.erb
<h1>New Business</h1>

<%= render 'form', business: @business %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<p>
  <strong>Company full name:</strong>
  <%= @business.company_full_name %>
</p>

<p>
  <strong>Company short name:</strong>
  <%= @business.company_short_name %>
</p>

<p>
  <strong>Signatory person:</strong>
  <%= @business.signatory_person %>
</p>

<p>
  <strong>Signatory basis:</strong>
  <%= @business.signatory_basis %>
</p>

<p>
  <strong>Inn:</strong>
  <%= @business.inn %>
</p>

<p>
  <strong>Kpp:</strong>
  <%= @business.kpp %>
</p>

<p>
  <strong>Ogrn:</strong>
  <%= @business.ogrn %>
</p>

<p>
  <strong>Legal address:</strong>
  <%= @business.legal_address %>
</p>

<p>
  <strong>Real address:</strong>
  <%= @business.real_address %>
</p>

<p>
  <strong>Post address:</strong>
  <%= @business.post_address %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @business.owner %>
</p>

<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>

<h1>Bank Accounts</h1>

<table class="table table-striped">
  <thead class="thead-dark">
  <tr>
    <th>Accountable</th>
    <th>Active</th>
    <th>Bank name</th>
    <th>Bank bik</th>
    <th>Kor account</th>
    <th>Account</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @bank_accounts.each do |bank_account| %>
    <tr>
      <td><%= bank_account.accountable %></td>
      <td><%= bank_account.active %></td>
      <td><%= bank_account.bank_name %></td>
      <td><%= bank_account.account_num %></td>
      <td><%= link_to 'Show', polymorphic_path([@business, bank_account]) %></td>
      <td><%= link_to 'Edit', edit_polymorphic_path([@business, bank_account]) %></td>
      <td><%= link_to 'Destroy', polymorphic_path([@business, bank_account]), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bank Account', new_polymorphic_path([@business, BankAccount]), class: 'btn btn-primary' %>