config/routes.rb
Rails.application.routes.draw do
  concern :accountable do
    resources :bank_accounts, except: :index
  end

  resources :counterparties, concerns: :accountable
  resources :businesses, concerns: :accountable
  resources :document_templates
  resources :documents, except: :new do
    get 'new/:type', to: 'documents#new', as: :new, on: :collection
  end

  devise_for :users

  authenticated :user do
    root to: "dashboard#show", as: :authenticated_root
  end

  root to: "pages#home"
end

app/models/counterparty.rb
class Counterparty < ApplicationRecord
  include Accountable
  include Ownerable

  has_many :documents, dependent: :destroy

  validates :company_full_name, :company_short_name, presence: true

  def to_s
    company_full_name
  end
end

app/controllers/counterparties_controller.rb
class CounterpartiesController < CustomerController
  before_action :set_counterparty, only: [:show, :edit, :update, :destroy]

  # GET /counterparties
  # GET /counterparties.json
  def index
    @counterparties = current_user.counterparties
  end

  # GET /counterparties/1
  # GET /counterparties/1.json
  def show
  end

  # GET /counterparties/new
  def new
    @counterparty = Counterparty.new
  end

  # GET /counterparties/1/edit
  def edit
  end

  # POST /counterparties
  # POST /counterparties.json
  def create
    @counterparty = Counterparty.new(counterparty_params)
    @counterparty.owner = current_user

    respond_to do |format|
      if @counterparty.save
        format.html { redirect_to @counterparty, notice: "Counterparty was successfully created." }
        format.json { render :show, status: :created, location: @counterparty }
      else
        format.html { render :new }
        format.json { render json: @counterparty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /counterparties/1
  # PATCH/PUT /counterparties/1.json
  def update
    respond_to do |format|
      if @counterparty.update(counterparty_params)
        format.html { redirect_to @counterparty, notice: "Counterparty was successfully updated." }
        format.json { render :show, status: :ok, location: @counterparty }
      else
        format.html { render :edit }
        format.json { render json: @counterparty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /counterparties/1
  # DELETE /counterparties/1.json
  def destroy
    @counterparty.destroy
    respond_to do |format|
      format.html { redirect_to counterparties_url, notice: "Counterparty was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_counterparty
    @counterparty = Counterparty.find(params[:id])
    @bank_accounts = @counterparty.bank_accounts
  end

  # Only allow a list of trusted parameters through.
  def counterparty_params
    params.require(:counterparty).permit(:company_full_name, :company_short_name, :signatory_person, :signatory_person_genitive, :signatory_basis, :signatory_basis_genitive, :inn, :kpp, :ogrn, :legal_address, :real_address, :post_address, :phone, :email)
  end
end

app/views/counterparties/_form.html.erb
<%= simple_form_for(@counterparty) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :company_full_name %>
    <%= f.input :company_short_name %>
    <%= f.input :signatory_person %>
    <%= f.input :signatory_person_genitive %>
    <%= f.input :signatory_basis %>
    <%= f.input :signatory_basis_genitive %>
    <%= f.input :inn %>
    <%= f.input :kpp %>
    <%= f.input :ogrn %>
    <%= f.input :legal_address %>
    <%= f.input :real_address %>
    <%= f.input :post_address %>
    <%= f.input :phone %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/counterparties/edit.html.erb
<h1>Editing Counterparty</h1>

<%= render 'form', counterparty: @counterparty %>

<%= link_to 'Show', @counterparty %> |
<%= link_to 'Back', counterparties_path %>

app/views/counterparties/index.html.erb
<h1>Counterparties</h1>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th>Company name</th>
      <th>Inn</th>
      <th>Kpp</th>
      <th>Ogrn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @counterparties.each do |counterparty| %>
      <tr>
        <td><%= counterparty.company_short_name %></td>
        <td><%= counterparty.inn %></td>
        <td><%= counterparty.kpp %></td>
        <td><%= counterparty.ogrn %></td>
        <td><%= link_to 'Show', counterparty %></td>
        <td><%= link_to 'Edit', edit_counterparty_path(counterparty) %></td>
        <td><%= link_to 'Destroy', counterparty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Counterparty', new_counterparty_path, class: 'btn btn-primary' %>

app/views/counterparties/new.html.erb
<h1>New Counterparty</h1>

<%= render 'form', counterparty: @counterparty %>

<%= link_to 'Back', counterparties_path %>

app/views/counterparties/show.html.erb
<p>
  <strong>Company full name:</strong>
  <%= @counterparty.company_full_name %>
</p>

<p>
  <strong>Company short name:</strong>
  <%= @counterparty.company_short_name %>
</p>

<p>
  <strong>Signatory person:</strong>
  <%= @counterparty.signatory_person %>
</p>

<p>
  <strong>Signatory basis:</strong>
  <%= @counterparty.signatory_basis %>
</p>

<p>
  <strong>Inn:</strong>
  <%= @counterparty.inn %>
</p>

<p>
  <strong>Kpp:</strong>
  <%= @counterparty.kpp %>
</p>

<p>
  <strong>Ogrn:</strong>
  <%= @counterparty.ogrn %>
</p>

<p>
  <strong>Legal address:</strong>
  <%= @counterparty.legal_address %>
</p>

<p>
  <strong>Real address:</strong>
  <%= @counterparty.real_address %>
</p>

<p>
  <strong>Post address:</strong>
  <%= @counterparty.post_address %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @counterparty.owner %>
</p>

<%= link_to 'Edit', edit_counterparty_path(@counterparty) %> |
<%= link_to 'Back', counterparties_path %>

<h1>Bank Accounts</h1>

<table class="table table-striped">
  <thead class="thead-dark">
  <tr>
    <th>Accountable</th>
    <th>Active</th>
    <th>Bank name</th>
    <th>Bank bik</th>
    <th>Kor account</th>
    <th>Account</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @bank_accounts.each do |bank_account| %>
    <tr>
      <td><%= bank_account.accountable %></td>
      <td><%= bank_account.active %></td>
      <td><%= bank_account.bank_name %></td>
      <td><%= bank_account.account_num %></td>
      <td><%= link_to 'Show', polymorphic_path([@counterparty, bank_account]) %></td>
      <td><%= link_to 'Edit', edit_polymorphic_path([@counterparty, bank_account]) %></td>
      <td><%= link_to 'Destroy', polymorphic_path([@counterparty, bank_account]), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bank Account', new_polymorphic_path([@counterparty, BankAccount]), class: 'btn btn-primary' %>