config/routes.rb
Rails.application.routes.draw do
  concern :accountable do
    resources :bank_accounts, except: :index
  end

  resources :counterparties, concerns: :accountable
  resources :businesses, concerns: :accountable
  resources :document_templates
  resources :documents, except: :new do
    get 'new/:type', to: 'documents#new', as: :new, on: :collection
  end

  devise_for :users

  authenticated :user do
    root to: "dashboard#show", as: :authenticated_root
  end

  root to: "pages#home"
end

app/models/document.rb
class Document < ApplicationRecord
  include Ownerable

  belongs_to :template, class_name: "DocumentTemplate"
  belongs_to :business
  belongs_to :counterparty

  has_one_attached :doc

  store_accessor :json_fields, :name, :surname, :type, :date

  def date
    return Time.zone.parse(super) if super.is_a?(String)
  end

  def virtual_fields 
    {
    'name': 'first_name', 
    'surname': 'second_name', 
    'type': 'string',
    'date': 'date'
    }
  end  

 
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = current_user.documents
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Contract.new
    @type = params[:type]
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)
    @document.owner = current_user

    respond_to do |format|
      if @document.save
        create_from_template(@document)

        format.html { redirect_to @document, notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        create_from_template(@document)

        format.html { redirect_to @document, notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_document
    @document = Document.find(params[:id])
  end

  def create_from_template(doc)
    CreateDocumentFromTemplateJob.perform_now(doc)
  end

  # Only allow a list of trusted parameters through.
  def document_params
    params.require(:document).permit(:type, :document_name, :customer, :executor)
  end
end

app/views/documents/_form.html.erb
<%= simple_form_for(@document, url: new_documents_path) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
      <%= f.input :document_name, as: :string %>
      <%= f.input :customer, as: :string %>
      <%= f.input :executor, as: :string %>
    </div>

 <%= @type %>
 <%= f.hidden_field :type, value: @type.classify%>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<h1>Documents</h1>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th>Template</th>
      <th>Business</th>
      <th>Counterparty</th>
      <th>Document number</th>
      <th>Signing date</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.template %></td>
        <td><%= document.business.company_short_name %></td>
        <td><%= document.counterparty.company_short_name %></td>
        <td><%= document.contract_num %></td>
        <td><%= document.signing_date %></td>
        <td><%= link_to 'Download', document %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contract', new_documents_path(type: 'contract'), class: 'btn btn-primary' %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p>
  <strong>Template:</strong>
  <%= @document.template.name %>
</p>

<p>
  <strong>Business:</strong>
  <%= @document.business %>
</p>

<p>
  <strong>Counterparty:</strong>
  <%= @document.counterparty %>
</p>

<p>
  <strong>Signing date:</strong>
  <%= @document.signing_date %>
</p>

<p>
  <strong>Download: </strong>
  <%= link_to 'document', @document.doc %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>