config/routes.rb
Rails.application.routes.draw do
  concern :accountable do
    resources :bank_accounts, except: :index
  end

  resources :counterparties, concerns: :accountable
  resources :businesses, concerns: :accountable
  resources :document_templates
  resources :documents, except: :new do
    get 'new/:type', to: 'documents#new', as: :new, on: :collection
  end

  devise_for :users

  authenticated :user do
    root to: "dashboard#show", as: :authenticated_root
  end

  root to: "pages#home"
end

app/views/layouts/_app_footer.html.erb
<div class="footer my-md-4">
  <div class="container">
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-9">
        <span class="copyright float-right">
          ©
          <script language="JavaScript">
              document.write(new Date().getFullYear())
          </script>, made with
          <i class="fa fa-heart heart"></i>
          by
          <a href="https://progress-engine.com/" target="_blank">Progress Engine</a>
        </span>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_app_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <%= link_to 'Templater', root_path, class: 'navbar-brand' %>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <%= active_link_to 'Templates', document_templates_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= active_link_to 'Businesses', businesses_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= active_link_to 'Counterparties', counterparties_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= active_link_to 'Docs', documents_path, class: 'nav-link' %>
      </li>
    </ul>

    <ul class="navbar-nav">
      <%- if signed_in? %>
        <li class="nav-item dropdown">
          <a aria-expanded="false" aria-haspopup="true" id="navbarDropdown" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button">
            <%= current_user.to_s %>
          </a>
          <div class="dropdown-menu dropdown-info" aria-labelledby="navbarDropdown">
            <%= active_link_to 'Edit account', edit_user_registration_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= active_link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= active_link_to 'Login', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= active_link_to 'Register', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>

  </div>
</nav>

app/views/layouts/_flash.html.erb
<div class="container">
    <%- flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
            <%= value %>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Templater</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body>
    <header>
      <%= render 'layouts/app_header' %>
    </header>

    <main class="internal">
      <%= render 'layouts/flash'%>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <footer>
      <%= render 'layouts/app_footer' %>
    </footer>
  </body>
</html>